redhat-cop/cloud.aws_ops

.github/workflows/integration.yml, .gitignore, test-requirements.txt, tests/integration/targets/setup_rsa_keys/handlers/main.yml, tests/integration/targets/setup_rsa_keys/tasks/main.yml, tests/integration/targets/test_customized_ami/defaults/main.yml, tests/integration/targets/test_customized_ami/meta/main.yml, tests/integration/targets/test_customized_ami/tasks/create_infra.yml, tests/integration/targets/test_customized_ami/tasks/main.yml
Integration test target `test_customized_ami` is failing due to missing RSA keys files `~/.ssh/id_rsa` and `~/.ssh/id_rsa.pub`
This pull request add a new test role to generate RSA keys prior to running integration tests.
This has been tested via pull request https://github.com/redhat-cop/cloud.aws_ops/pull/47
=> Fix test_customized_ami - add missing RSA public and private ssh keys

.github/workflows/sanity.yml
Add an exclude for 3.9 to devel to avoid sanity test failures on devel
example: https://github.com/redhat-cop/cloud.aws_ops/actions/runs/5511317186/jobs/10048840426
=> Add 3.9 to exclude from devel

.github/workflows/integration.yml
`safe-to-test` workflow allows PRs from contributors to run automatically, but that requires community contributions to be approved before running.
Validated via #68
=> CI - add safe to test workflow

.github/workflows/integration.yml, test-requirements.txt, tests/integration/requirements.yml
- `splitter` this job identifies the tests impacted by the change so that we do not need to run the full test suite for every single pull request
=> CI - Integration tests updates

changelogs/fragments/fix_manage_vpc_peering_integration_test.yml, roles/manage_vpc_peering/README.md, roles/manage_vpc_peering/tasks/accept.yaml, roles/manage_vpc_peering/tasks/create.yaml, roles/manage_vpc_peering/tasks/delete.yaml, roles/manage_vpc_peering/tasks/main.yaml, tests/integration/targets/test_manage_vpc_peering/aliases, tests/integration/targets/test_manage_vpc_peering/defaults/main.yml, tests/integration/targets/test_manage_vpc_peering/tasks/create_delete_accept_peering.yml, tests/integration/targets/test_manage_vpc_peering/tasks/main.yml, tests/integration/targets/test_manage_vpc_peering/tasks/setup.yml, tests/integration/targets/test_manage_vpc_peering/tasks/teardown.yml, tests/integration/targets/test_manage_vpc_peering/tasks/validate.yml
Fix integration tests for `manage_vpc_peering` role.
=> manage_vpc_peering: fix integration tests, update role var names

README.md, changelogs/fragments/awsconfig_apigateway.yml, roles/awsconfig_apigateway_with_lambda_integration/README.md, roles/awsconfig_apigateway_with_lambda_integration/defaults/main.yml, roles/awsconfig_apigateway_with_lambda_integration/files/lambda_trust_policy.json, roles/awsconfig_apigateway_with_lambda_integration/meta/main.yml, roles/awsconfig_apigateway_with_lambda_integration/tasks/apigateway.yml, roles/awsconfig_apigateway_with_lambda_integration/tasks/lambda.yml, roles/awsconfig_apigateway_with_lambda_integration/tasks/main.yml, roles/awsconfig_apigateway_with_lambda_integration/templates/swagger.json.j2, tests/integration/targets/test_awsconfig_apigateway_with_lambda_integration/aliases, tests/integration/targets/test_awsconfig_apigateway_with_lambda_integration/defaults/main.yml, tests/integration/targets/test_awsconfig_apigateway_with_lambda_integration/files/server.py, tests/integration/targets/test_awsconfig_apigateway_with_lambda_integration/tasks/main.yml
A Role to create an API gateway with Lambda proxy integration
=> awsconfig_apigateway_with_lambda_integration - new role

changelogs/fragments/20230804-backup-role-bugfixes.yaml, roles/backup_create_plan/README.md, roles/backup_select_resources/README.md, roles/backup_select_resources/tasks/main.yaml
Fix READMEs in both backup roles, add all needed IAM service role policies when creating a new IAM role in `backup_select_resources` role.
=> Backup role bugfixes

.github/workflows/sanity.yml, changelogs/fragments/20230823-update-ci-sanity-test-matrix.yaml
The milestone and devel branches of ansible no longer support python 3.9. This PR adds milestone/python 3.9 to matrix_exclude in the sanity test Github Actions workflow.
Bugfix Pull Request
=> Exclude python 3.9 for milestone in sanity test matrix

changelogs/fragments/aws_setup_credentials_add_no_log.yml, roles/aws_setup_credentials/tasks/read_option.yml
Add no_log to aws_setup_credentials role in cloud.aws_ops to prevent credential leak.
This PR has been tested locally to verify the results.
To test, run any integration tests and verify that aws_setup_credentials role's tasks don't print out credentials in the output logs.
=> aws_setup_credentials: add no_log

changelogs/fragments/transit_gateway_doc_update.yaml, roles/manage_transit_gateway/README.md, roles/manage_transit_gateway/meta/argument_specs.yaml
=> Update README of manage_transit_gateway role

.github/workflows/integration.yml
The ansible version currently used was not able to install the required collections to run integration, this fix aims to fix that by using `milestone` (which required Python >= 3.9)
This has been successfully validated via PR #101
=> Fix Integration tests - collection dependency install

changelogs/fragments/backup_select_resource_bug_fix.yml, changelogs/fragments/fix_rds_db_version.yml, playbooks/webapp/README.md, playbooks/webapp/vars/main.yaml, roles/backup_select_resources/tasks/main.yaml, tests/integration/targets/test_deploy_flask_app/roles/run_deploy_flask_app/tasks/create.yaml, tests/integration/targets/test_deploy_flask_app/roles/run_deploy_flask_app/vars/main.yaml, tests/integration/targets/test_deploy_flask_app/runme.sh
This PR fixes the [integration test failures](https://github.com/redhat-cop/cloud.aws_ops/actions/runs/8802357180/job/24157886634?pr=111) for the following roles
deploy_flask_app:
The Postgres DB engine version 14.8 has been removed and replaced with version 16.2.
backup_select_resources:
Incorrect mention of a dict attribute has been rectified with the right one
=> Fix test failures in deploy_flask_app and backup_select_resources roles

README.md, changelogs/fragments/doc_link_update.yml, playbooks/README.md, playbooks/UPLOAD_FILE_TO_S3.md, playbooks/move_vm_from_on_prem_to_aws/README.md, playbooks/webapp/README.md, roles/aws_setup_credentials/README.md, roles/awsconfig_apigateway_with_lambda_integration/README.md, roles/awsconfig_detach_and_delete_internet_gateway/README.md, roles/awsconfig_multiregion_cloudtrail/README.md, roles/backup_create_plan/README.md, roles/backup_select_resources/README.md, roles/clone_on_prem_vm/README.md, roles/create_rds_global_cluster/README.md, roles/customized_ami/README.md, roles/deploy_flask_app/README.md, roles/ec2_instance_terminate_by_tag/README.md, roles/enable_cloudtrail_encryption_with_kms/README.md, roles/import_image_and_run_aws_instance/README.md, roles/manage_transit_gateway/README.md, roles/manage_vpc_peering/README.md, roles/move_objects_between_buckets/README.md
This PR corrects some of the incorrect links and updates all links to relative ones.
=> Update links in the README

galaxy.yml
Since stable-3 has been created, update the galaxy.yml version to 4.0.0-dev0.
=> Update version to point to the next major release in the galaxy.yml file

roles/ec2_networking_resources/README.md, roles/ec2_networking_resources/defaults/main.yml, roles/ec2_networking_resources/meta/argument_specs.yml, roles/ec2_networking_resources/meta/main.yml, roles/ec2_networking_resources/tasks/main.yml, tests/integration/targets/test_ec2_networking_resources/aliases, tests/integration/targets/test_ec2_networking_resources/defaults/main.yml, tests/integration/targets/test_ec2_networking_resources/tasks/main.yml
This adds a new role to create a basic set of networking resources. This is designed to be used with a role to create an EC2 instance.
See: https://issues.redhat.com/browse/ACA-1958
=> Add new ec2_networking_resources role

changelogs/fragments/add_module_defaults_ec2_networking_resource.yml, roles/ec2_networking_resources/tasks/main.yml
This PR adds  module_defaults to ec2_networking_resources role which is necessary for correctly setting the aws_setup_credentials.
=> Add module_defaults to ec2_networking_resources role

extensions/patterns/configure_ec2/README.md, extensions/patterns/configure_ec2/playbooks/create_ec2_instance.yml, extensions/patterns/configure_ec2/playbooks/group_vars/all.yml, extensions/patterns/configure_ec2/template_surveys/create_ec2_instance.yml, roles/manage_ec2_instance/README.md, roles/manage_ec2_instance/tasks/ec2_instance_create_operations.yml
Refer : https://issues.redhat.com/browse/ACA-2059
This PR  ensures that private keys to ec2 instances are not available in job logs by default
=> Add security for keypair creation in configure_ec2 pattern

extensions/patterns/configure_ec2/playbooks/create_ec2_instance.yml, extensions/patterns/configure_ec2/template_surveys/terminate_ec2_instance.yml, roles/manage_ec2_instance/tasks/ec2_instance_create_operations.yml
Two updates:
- We can't use the var `key_info_result` in the pattern playbook, because it gets overwritten by the included role playbook.
- It's ok to log the `ec2_key_info` output because that doesn't include the private key, and if there's an error with the key (for example if the user was expecting the key to be present) it's helpful to be able to see what the returned value was.
=> Small updates to ec2 pattern

changelogs/fragments/20250116-move-ee-from-dockerhub-to-quay.yaml, extensions/patterns/configure_ec2/exec_env/execution-environment.yml, extensions/patterns/configure_ec2/setup.yml
Ensure configure_ec2 pattern EE does not use DockerHub to pull or host images
The container image has been moved from DockerHub to quay.io
=> Update container image registry: docker.io -> quay.io

changelogs/fragments/2024-12-04_ec2_networking_role_add_options.yml, changelogs/fragments/20250116-move-ee-from-dockerhub-to-quay.yaml, roles/ec2_networking_resources/meta/argument_specs.yml
This pull request contains the following changes:
- add ``version_added`` to role ``ec2_networking_resources``for the role to be listed in the release changelog
- The role ``ec2_networking_resources`` and the ec2 pattern have not yet been released, we must remove the changelog file describing changes on these new features.
=> roles/ec2_networking_resources - add ``version_added``

.config/ansible-lint.yml, .github/workflows/linters.yml, changelogs/fragments/20250127-fix-ansible-lint.yaml
Fixing CI issue from Release PR https://github.com/redhat-cop/cloud.aws_ops/pull/150
Update to ansible-lint `24.12.2` to fix ansible-lint. The previous version does not ignore the directory `test/integration`
See https://github.com/redhat-cop/cloud.aws_ops/actions/runs/12993916513/job/36237187718?pr=150
=> CI - fix ansible-lint issues
